### ISSUE TITLE
Pendelton.html

### ISSUE THREAD

**Issue by AshtonSnapp** [TheAngelReturns/aliceos-docs#1]
When I click on the "System Applet" link, it goes to a 404 page. Any link I click afterwards adds a /assets/ to the URL.

Example: https://docs.aliceos.app/applets/applets/applets/applets/applets/applets/applets/applets/applets/applets/applets/pendleton.html

The only way to get to another page from there is to type in the URL.

**Comment by alicerunsonfedora** [comment]
It appears that it keeps looping. I've just applied some changes, see if this fixes your issue.

**Comment by AshtonSnapp** [comment]
That worked! Thanks!
